source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Poddy_Example', :exclusive => true do
  pod 'Poddy', :path => '../'
end

target 'Poddy_Tests', :exclusive => true do
  pod 'Poddy', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
end
