source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Poddy_Example', :exclusive => true do
  pod 'Poddy', :path => '../'
end


target 'Poddy_Tests', :exclusive => true do
  pod 'Poddy', :path => '../'
end
